development: &default
  adapter: postgresql
  encoding: unicode
  database: brian_for_vice_president_development
  username: postgres
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: brian_for_vice_president_test
  min_messages: warning

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
